### ISSUE TITLE
센서에서 보내는 데이타를 웹 어디서 확인하나요?

### ISSUE THREAD

**Issue by choijaechul** [SKT-ThingPlug/thingplug-starter-kit#1]

**Comment by ThingPlug** [comment]
안녕하세요. SKT ThingPlug 입니다.
본 페이지는 아직 공식적으로 오픈 전이라 답변이 늦었습니다. 죄송합니다.

현재 Starter Kit에서는 센서 데이터는 application.js에서 확인하도록 되어 있습니다.
application.js에서 사용하는 방법을 이용하면 웹페이지에서 REST API로 센서 데이터를 불러올 수 있습니다. 

감사합니다.
