### ISSUE TITLE
error : conection refused

### ISSUE THREAD

**Issue by hoky5611** [SKT-ThingPlug/thingplug-starter-kit#25]
node.js 설치하고 

starter kit 디렉터리에서 config.js 설정하고 

node device.js 내리면

error : conection refused 발생합니다.

다른 설정이 더 필요한건지 문의 드립니다.
![error conection refused](https://cloud.githubusercontent.com/assets/21697810/21884960/ebae3e7c-d8f8-11e6-9b95-4cbd6553264f.jpg)

[config.zip](https://github.com/SKT-ThingPlug/thingplug-starter-kit/files/701267/config.zip)

**Comment by brianjang** [comment]
저도 같은 현상이 있어요.
=> mqtt.js 에서 인증이 실패해서 나오는 에러입니다.

config.js 수정 내용입니다.

userID : "sandbox.sktiot.com의 log-in ID 입력"

uKey : "마이페이지 -> 사용자 인증키 값을 입력"

nodeID : '0.2.481.1.101.01012345678' // 실제 전화번호 입력

passCode : '주민번호앞6자리 입력',

**Comment by brianjang** [comment]
please see the patch as below : (you can resolve this issue)
https://github.com/SKT-ThingPlug/thingplug-starter-kit/pull/27

**Comment by ThingPlug** [comment]
서버 인증 변경으로 인해 패치 진행되었습니다.
감사합니다.
